/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IBscBridgeAgent } from "../IBscBridgeAgent";

export class IBscBridgeAgent__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBscBridgeAgent {
    return new Contract(address, _abi, signerOrProvider) as IBscBridgeAgent;
  }
}

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "metisTxHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "swapType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exchange",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
    ],
    name: "swapFilled",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "spender",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "metisTxHash",
        type: "bytes32",
      },
      {
        indexed: false,
        internalType: "string",
        name: "swapType",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "base",
        type: "string",
      },
      {
        indexed: false,
        internalType: "string",
        name: "quote",
        type: "string",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "fee",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "exchange",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "nonce",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "swapStarted",
    type: "event",
  },
  {
    inputs: [],
    name: "bnbBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "bnbWithdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "string",
            name: "swapType",
            type: "string",
          },
          {
            internalType: "string",
            name: "base",
            type: "string",
          },
          {
            internalType: "string",
            name: "quote",
            type: "string",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "fee",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "exchange",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "nonce",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "deadline",
            type: "uint256",
          },
          {
            internalType: "address",
            name: "account",
            type: "address",
          },
        ],
        internalType: "struct IMessageStructure.Message",
        name: "message",
        type: "tuple",
      },
      {
        internalType: "bytes32",
        name: "metisTxHash",
        type: "bytes32",
      },
    ],
    name: "fillBNB2TOTMPegin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_pancakePair",
        type: "address",
      },
    ],
    name: "setPancakePair",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_slippagePercentage",
        type: "uint256",
      },
    ],
    name: "setSlippagePercentage",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "swapRouterQuery",
    outputs: [
      {
        internalType: "uint256",
        name: "baseReserved",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "quoteReserved",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "exchange",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totemBalance",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
