/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface IBscBridgeAgentInterface extends ethers.utils.Interface {
  functions: {
    "bnbBalance()": FunctionFragment;
    "bnbWithdraw()": FunctionFragment;
    "fillBNB2TOTMPegin(tuple,bytes32)": FunctionFragment;
    "setPancakePair(address)": FunctionFragment;
    "setSlippagePercentage(uint256)": FunctionFragment;
    "swapRouterQuery(uint256)": FunctionFragment;
    "totemBalance()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "bnbBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bnbWithdraw",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fillBNB2TOTMPegin",
    values: [
      {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPancakePair",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippagePercentage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapRouterQuery",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totemBalance",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "bnbBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bnbWithdraw",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fillBNB2TOTMPegin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPancakePair",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippagePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapRouterQuery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totemBalance",
    data: BytesLike
  ): Result;

  events: {
    "swapFilled(address,bytes32,string,uint256,uint256,uint256,uint256)": EventFragment;
    "swapStarted(address,bytes32,string,string,string,uint256,uint256,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "swapFilled"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "swapStarted"): EventFragment;
}

export class IBscBridgeAgent extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IBscBridgeAgentInterface;

  functions: {
    bnbBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "bnbBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    bnbWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "bnbWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    fillBNB2TOTMPegin(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "fillBNB2TOTMPegin((string,string,string,uint256,uint256,uint256,uint256,uint256,address),bytes32)"(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setPancakePair(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setPancakePair(address)"(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setSlippagePercentage(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "setSlippagePercentage(uint256)"(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapRouterQuery(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "swapRouterQuery(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    totemBalance(overrides?: CallOverrides): Promise<[BigNumber]>;

    "totemBalance()"(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  bnbBalance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "bnbBalance()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  bnbWithdraw(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "bnbWithdraw()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  fillBNB2TOTMPegin(
    message: {
      swapType: string;
      base: string;
      quote: string;
      amount: BigNumberish;
      fee: BigNumberish;
      exchange: BigNumberish;
      nonce: BigNumberish;
      deadline: BigNumberish;
      account: string;
    },
    metisTxHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "fillBNB2TOTMPegin((string,string,string,uint256,uint256,uint256,uint256,uint256,address),bytes32)"(
    message: {
      swapType: string;
      base: string;
      quote: string;
      amount: BigNumberish;
      fee: BigNumberish;
      exchange: BigNumberish;
      nonce: BigNumberish;
      deadline: BigNumberish;
      account: string;
    },
    metisTxHash: BytesLike,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setPancakePair(
    _pancakePair: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setPancakePair(address)"(
    _pancakePair: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setSlippagePercentage(
    _slippagePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "setSlippagePercentage(uint256)"(
    _slippagePercentage: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapRouterQuery(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "swapRouterQuery(uint256)"(
    amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  totemBalance(overrides?: CallOverrides): Promise<BigNumber>;

  "totemBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    bnbBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "bnbBalance()"(overrides?: CallOverrides): Promise<BigNumber>;

    bnbWithdraw(overrides?: CallOverrides): Promise<void>;

    "bnbWithdraw()"(overrides?: CallOverrides): Promise<void>;

    fillBNB2TOTMPegin(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "fillBNB2TOTMPegin((string,string,string,uint256,uint256,uint256,uint256,uint256,address),bytes32)"(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setPancakePair(
      _pancakePair: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "setPancakePair(address)"(
      _pancakePair: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setSlippagePercentage(
      _slippagePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "setSlippagePercentage(uint256)"(
      _slippagePercentage: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    swapRouterQuery(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        baseReserved: BigNumber;
        quoteReserved: BigNumber;
        exchange: BigNumber;
      }
    >;

    "swapRouterQuery(uint256)"(
      amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber] & {
        baseReserved: BigNumber;
        quoteReserved: BigNumber;
        exchange: BigNumber;
      }
    >;

    totemBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "totemBalance()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {
    swapFilled(
      recipient: string | null,
      metisTxHash: BytesLike | null,
      swapType: null,
      amount: null,
      fee: null,
      exchange: null,
      nonce: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber, BigNumber, BigNumber],
      {
        recipient: string;
        metisTxHash: string;
        swapType: string;
        amount: BigNumber;
        fee: BigNumber;
        exchange: BigNumber;
        nonce: BigNumber;
      }
    >;

    swapStarted(
      spender: string | null,
      metisTxHash: BytesLike | null,
      swapType: null,
      base: null,
      quote: null,
      amount: null,
      fee: null,
      exchange: null,
      nonce: null,
      deadline: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        spender: string;
        metisTxHash: string;
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumber;
        fee: BigNumber;
        exchange: BigNumber;
        nonce: BigNumber;
        deadline: BigNumber;
      }
    >;
  };

  estimateGas: {
    bnbBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "bnbBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    bnbWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "bnbWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    fillBNB2TOTMPegin(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "fillBNB2TOTMPegin((string,string,string,uint256,uint256,uint256,uint256,uint256,address),bytes32)"(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setPancakePair(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setPancakePair(address)"(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setSlippagePercentage(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "setSlippagePercentage(uint256)"(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapRouterQuery(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "swapRouterQuery(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    totemBalance(overrides?: CallOverrides): Promise<BigNumber>;

    "totemBalance()"(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    bnbBalance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "bnbBalance()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    bnbWithdraw(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "bnbWithdraw()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    fillBNB2TOTMPegin(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "fillBNB2TOTMPegin((string,string,string,uint256,uint256,uint256,uint256,uint256,address),bytes32)"(
      message: {
        swapType: string;
        base: string;
        quote: string;
        amount: BigNumberish;
        fee: BigNumberish;
        exchange: BigNumberish;
        nonce: BigNumberish;
        deadline: BigNumberish;
        account: string;
      },
      metisTxHash: BytesLike,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setPancakePair(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setPancakePair(address)"(
      _pancakePair: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setSlippagePercentage(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "setSlippagePercentage(uint256)"(
      _slippagePercentage: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapRouterQuery(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "swapRouterQuery(uint256)"(
      amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    totemBalance(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "totemBalance()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
