/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface MetisBridgeAgentProxyInterface extends ethers.utils.Interface {
  functions: {
    "disableUpgrade()": FunctionFragment;
    "domain()": FunctionFragment;
    "enableUpgrade()": FunctionFragment;
    "initialize(string,string,address)": FunctionFragment;
    "metisBridgeAgentImpl()": FunctionFragment;
    "owner()": FunctionFragment;
    "peggedTotemTokenProxy()": FunctionFragment;
    "proxyAdmin()": FunctionFragment;
    "swapDataMap(address,bytes32)": FunctionFragment;
    "swapNonce(address)": FunctionFragment;
    "upgradeEnabled()": FunctionFragment;
    "upgradeTo(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "disableUpgrade",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "domain", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "enableUpgrade",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "metisBridgeAgentImpl",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "peggedTotemTokenProxy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxyAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "swapDataMap",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "swapNonce", values: [string]): string;
  encodeFunctionData(
    functionFragment: "upgradeEnabled",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "upgradeTo", values: [string]): string;

  decodeFunctionResult(
    functionFragment: "disableUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "domain", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "enableUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "metisBridgeAgentImpl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "peggedTotemTokenProxy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proxyAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapDataMap",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swapNonce", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeEnabled",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "upgradeTo", data: BytesLike): Result;

  events: {
    "ImplementationUpgraded(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ImplementationUpgraded"): EventFragment;
}

export class MetisBridgeAgentProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: MetisBridgeAgentProxyInterface;

  functions: {
    disableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "disableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
      }
    >;

    "domain()"(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
      }
    >;

    enableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "enableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    initialize(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "initialize(string,string,address)"(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    metisBridgeAgentImpl(overrides?: CallOverrides): Promise<[string]>;

    "metisBridgeAgentImpl()"(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    peggedTotemTokenProxy(overrides?: CallOverrides): Promise<[string]>;

    "peggedTotemTokenProxy()"(overrides?: CallOverrides): Promise<[string]>;

    proxyAdmin(overrides?: CallOverrides): Promise<[string]>;

    "proxyAdmin()"(overrides?: CallOverrides): Promise<[string]>;

    swapDataMap(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        txHash: string;
        nonce: BigNumber;
        exchange: BigNumber;
        swapType: string;
        isFilled: boolean;
        isClaimed: boolean;
      }
    >;

    "swapDataMap(address,bytes32)"(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        txHash: string;
        nonce: BigNumber;
        exchange: BigNumber;
        swapType: string;
        isFilled: boolean;
        isClaimed: boolean;
      }
    >;

    swapNonce(arg0: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    "swapNonce(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    upgradeEnabled(overrides?: CallOverrides): Promise<[boolean]>;

    "upgradeEnabled()"(overrides?: CallOverrides): Promise<[boolean]>;

    upgradeTo(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    "upgradeTo(address)"(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  disableUpgrade(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "disableUpgrade()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  domain(
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string] & {
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
    }
  >;

  "domain()"(
    overrides?: CallOverrides
  ): Promise<
    [string, string, BigNumber, string] & {
      name: string;
      version: string;
      chainId: BigNumber;
      verifyingContract: string;
    }
  >;

  enableUpgrade(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "enableUpgrade()"(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  initialize(
    _name: string,
    _version: string,
    _peggedTotemTokenProxy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "initialize(string,string,address)"(
    _name: string,
    _version: string,
    _peggedTotemTokenProxy: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  metisBridgeAgentImpl(overrides?: CallOverrides): Promise<string>;

  "metisBridgeAgentImpl()"(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  peggedTotemTokenProxy(overrides?: CallOverrides): Promise<string>;

  "peggedTotemTokenProxy()"(overrides?: CallOverrides): Promise<string>;

  proxyAdmin(overrides?: CallOverrides): Promise<string>;

  "proxyAdmin()"(overrides?: CallOverrides): Promise<string>;

  swapDataMap(
    arg0: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string, boolean, boolean] & {
      txHash: string;
      nonce: BigNumber;
      exchange: BigNumber;
      swapType: string;
      isFilled: boolean;
      isClaimed: boolean;
    }
  >;

  "swapDataMap(address,bytes32)"(
    arg0: string,
    arg1: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    [string, BigNumber, BigNumber, string, boolean, boolean] & {
      txHash: string;
      nonce: BigNumber;
      exchange: BigNumber;
      swapType: string;
      isFilled: boolean;
      isClaimed: boolean;
    }
  >;

  swapNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

  "swapNonce(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  upgradeEnabled(overrides?: CallOverrides): Promise<boolean>;

  "upgradeEnabled()"(overrides?: CallOverrides): Promise<boolean>;

  upgradeTo(
    _newMetisBridgeAgentImpl: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  "upgradeTo(address)"(
    _newMetisBridgeAgentImpl: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    disableUpgrade(overrides?: CallOverrides): Promise<void>;

    "disableUpgrade()"(overrides?: CallOverrides): Promise<void>;

    domain(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
      }
    >;

    "domain()"(
      overrides?: CallOverrides
    ): Promise<
      [string, string, BigNumber, string] & {
        name: string;
        version: string;
        chainId: BigNumber;
        verifyingContract: string;
      }
    >;

    enableUpgrade(overrides?: CallOverrides): Promise<void>;

    "enableUpgrade()"(overrides?: CallOverrides): Promise<void>;

    initialize(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initialize(string,string,address)"(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: CallOverrides
    ): Promise<void>;

    metisBridgeAgentImpl(overrides?: CallOverrides): Promise<string>;

    "metisBridgeAgentImpl()"(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    peggedTotemTokenProxy(overrides?: CallOverrides): Promise<string>;

    "peggedTotemTokenProxy()"(overrides?: CallOverrides): Promise<string>;

    proxyAdmin(overrides?: CallOverrides): Promise<string>;

    "proxyAdmin()"(overrides?: CallOverrides): Promise<string>;

    swapDataMap(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        txHash: string;
        nonce: BigNumber;
        exchange: BigNumber;
        swapType: string;
        isFilled: boolean;
        isClaimed: boolean;
      }
    >;

    "swapDataMap(address,bytes32)"(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [string, BigNumber, BigNumber, string, boolean, boolean] & {
        txHash: string;
        nonce: BigNumber;
        exchange: BigNumber;
        swapType: string;
        isFilled: boolean;
        isClaimed: boolean;
      }
    >;

    swapNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "swapNonce(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeEnabled(overrides?: CallOverrides): Promise<boolean>;

    "upgradeEnabled()"(overrides?: CallOverrides): Promise<boolean>;

    upgradeTo(
      _newMetisBridgeAgentImpl: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "upgradeTo(address)"(
      _newMetisBridgeAgentImpl: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    ImplementationUpgraded(
      oldImpl: null,
      newImpl: null
    ): TypedEventFilter<[string, string], { oldImpl: string; newImpl: string }>;
  };

  estimateGas: {
    disableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "disableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    domain(overrides?: CallOverrides): Promise<BigNumber>;

    "domain()"(overrides?: CallOverrides): Promise<BigNumber>;

    enableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "enableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    initialize(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "initialize(string,string,address)"(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    metisBridgeAgentImpl(overrides?: CallOverrides): Promise<BigNumber>;

    "metisBridgeAgentImpl()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    peggedTotemTokenProxy(overrides?: CallOverrides): Promise<BigNumber>;

    "peggedTotemTokenProxy()"(overrides?: CallOverrides): Promise<BigNumber>;

    proxyAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    "proxyAdmin()"(overrides?: CallOverrides): Promise<BigNumber>;

    swapDataMap(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "swapDataMap(address,bytes32)"(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    swapNonce(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "swapNonce(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    upgradeEnabled(overrides?: CallOverrides): Promise<BigNumber>;

    "upgradeEnabled()"(overrides?: CallOverrides): Promise<BigNumber>;

    upgradeTo(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    "upgradeTo(address)"(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "disableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    domain(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "domain()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    enableUpgrade(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "enableUpgrade()"(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    initialize(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "initialize(string,string,address)"(
      _name: string,
      _version: string,
      _peggedTotemTokenProxy: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    metisBridgeAgentImpl(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "metisBridgeAgentImpl()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    peggedTotemTokenProxy(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "peggedTotemTokenProxy()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    proxyAdmin(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "proxyAdmin()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    swapDataMap(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "swapDataMap(address,bytes32)"(
      arg0: string,
      arg1: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    swapNonce(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "swapNonce(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeEnabled(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "upgradeEnabled()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    upgradeTo(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    "upgradeTo(address)"(
      _newMetisBridgeAgentImpl: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
